name: Build and test

on: [push, pull_request]

jobs:
  build_test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: "Setup .NET SDK"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Setup .NET 3.1 runtime
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -c Release --no-build
